### ISSUE TITLE
Abandoned or superseded?

### ISSUE THREAD

**Issue by rulatir** [pluto-build/pluto#15]
It seems there's been very little activity here over the last 4 years. Is this project completely abandoned, or has it been superseded by another project?

**Comment by seba--** [comment]
This project has been superseded by PIE: Pipelines for Interactive Environments, which is under active development.

Code: https://github.com/metaborg/pie

Papers:

 - PIE: A Domain-Specific Language for Interactive Software Development Pipelines 
Gabriël Konat, Michael J. Steindorfer, Sebastian Erdweg, and Eelco Visser. In Art, Science, and Engineering of Programming, 2(3). 2018. [ [pdf](https://www.pl.informatik.uni-mainz.de/files/2019/04/pie-design.pdf) ] 

- Scalable Incremental Building with Dynamic Task Dependencies
Gabriël Konat, Sebastian Erdweg, and Eelco Visser. In Proceedings of International Conference on Automated Software Engineering (ASE). ACM, 2018. [ [pdf](https://www.pl.informatik.uni-mainz.de/files/2019/04/pie-scalable-incremental-build.pdf) ]
